config/routes.rb
Shopscore::Application.routes.draw do
  match "/dashboard", :to => "dashboard#index"
  match "/beoordeel/:order_hash", :to => "orders#rate", :as => "rate"

  devise_for :users, :path => '', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resources :orders

  root :to => 'welcome#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :do_not_send_until, :email, :order_number, :remark, :rating, :sent, :shop_id
  acts_as_tenant(:shop)
  belongs_to :shop

  before_create :set_hash

  def set_hash
    self.order_hash = Digest::SHA1.hexdigest("#{self.id}#{Time.now}#{self.email}")
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :title, :url
  has_many :users
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :shop_id

  belongs_to :shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  set_current_tenant_through_filter
  layout 'dashboard'
  
  before_filter :authenticate_user!
  before_filter :set_shop_tenant

  def current_shop
    current_user.shop
  end
  
  def set_shop_tenant
    set_current_tenant(current_shop)
  end

  def index
    @latest_orders = Order.limit(10)
  end
end

app/controllers/orders_controller.rb
class OrdersController < DashboardController
  before_filter :reset_tenant, :only => [:rate, :update]
  before_filter :authenticate_user!, :except => [:rate, :update]
  layout 'application', :only => :rate

  def reset_tenant
    ActsAsTenant.current_tenant = nil
  end

  def rate
    @order = Order.find_by_order_hash(params[:order_hash])
  end


  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params[:order])

    if @order.save
      redirect_to dashboard_path
    else
      render "new"
    end
  end

  def update
    @order = Order.find(params[:id])

    if @order.update_attributes(params[:order])
      redirect_to root_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.haml
%h1 Dashboard

.well
  %table.table
    %thead
      %tr
        %th #
        %th Email
        %th Send On
        %th Rating
        %th Remark
        %th Is Sent
        %th Rating url
    %tbody
      - @latest_orders.each do |order|
        %tr
          %td=order.order_number
          %td=order.email
          %td=order.do_not_send_until
          %td
            - if order.rating
              = order.rating
            - else
              %i.icon-question-sign
          %td
            - if order.remark
              = order.remark
            - else
              %i.icon-question-sign
          %td
            - if order.sent
              %i.icon-ok-sign
              Sent
            - else
              %i.icon-time
              Scheduled
          %td
            = link_to rate_path(order.order_hash) do
              %i.icon-star

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Shopscore"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body

    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand{:href => "#"} ShopScore
          - if current_user
            .pull-right
              =link_to dashboard_path, :class => "btn btn-primary" do
                DASHBOARD
                %i.icon-circle-arrow-right
          - else
            = form_tag user_session_path, :class => "navbar-form pull-right" do
              = text_field_tag 'user[email]', nil, :placeholder => "Email", :class => "span2"
              = password_field_tag 'user[password]', nil, :placeholder => "Password", :class => "span2"
              %button.btn Sign in
    .container
      .row
        .span12
          = bootstrap_flash
          = yield
      %hr
        %footer
          %p &copy; ShopScore 2012
    = javascript_include_tag "application"

app/views/layouts/dashboard.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Shopscore"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "dashboard", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand(href="#") Shopscore
          .container.nav-collapse
            %ul.nav.pull-right
              %li.divider-vertical
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  =current_user.email
                  %b.caret
                %ul.dropdown-menu
                  %li=link_to "Logout", destroy_user_session_path, :method => :delete


    .container

      .content
        .row
          .span12
            = bootstrap_flash
            = yield
    = javascript_include_tag "dashboard"

app/views/layouts/login.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Shopscore"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
  %body
    .container-fluid
      .row-fluid
        .span4
        .span3.well
          = bootstrap_flash
          = yield
        .span4

app/views/orders/new.html.haml
%h1 Order toevoegen

= simple_form_for(@order, :html => {:class => 'form-horizontal' }) do |form|
  = form.input :order_number
  = form.input :email
  = form.input :do_not_send_until
  .control-group
    .controls= form.button :submit, "Opslaan", :class => "btn btn-success"

app/views/orders/rate.html.haml
%h1 Beoordeel uw bestelling:
.lead Bedankt dat u ervoor heeft gekozen om uw bestelling te beoordelen.
%dl
  %dt Ordernummer
  %dd=@order.order_number
  %dt Bestelling geplaatst op
  %dd=@order.created_at

= simple_form_for(@order, :html => {:class => 'form-horizontal' }) do |form|
  .control-group
    = form.label :rating
    .controls.rating
      - (1..5).each do |i|
        %span.icon-star-empty{"data-rating" => i, :class => (@order.rating == i ? "active" : "")}
  = form.input :rating, :as => :hidden
  = form.input :remark, :input_html => {:rows => 5, :style => "width:300px;"}
  .control-group
    .controls= form.button :submit, "Beoordeling verzenden", :class => "btn btn-success"

app/views/welcome/index.html.haml
.hero-unit
  %h1 ShopScore
  .lead Easy customer feedback for your webshop.
  %p=link_to "Learn more &raquo;".html_safe, "/about", :class => "btn btn-primary btn-large"